const projects = [
  {
    title: 'STOOP',
    date: '2019/2020/in development',
    imageUrl: '../images/stoop.jpg',
    imageAlt: '',
    description: 'A social cat spotting app, for spotting Brooklyn stoop cats.',
    technologies: 'Node · Express · React · Redux · Google Maps API · PostgreSQL · Sequelize',
    team: 'Solo project. 2019/2020/in development.',
    github: '',
    deployed: null,
  },
  {
    title: 'CINDR',
    date: '2019',
    imageUrl: '../images/cindrScreenshot.png',
    imageAlt: 'A screenshot of a web application. A question on the screen, asking the user to choose between two answers.',
    description: 'A choose-your-own-adventure style dating app.',
    technologies: 'Phaser3 · React · Redux · Node · Express · PostgreSQL · Sequelize · Socket.io',
    team: 'Developed in collaboration with Petra Laohakul, Darshin Van Parijs, and Kimberly Zawacki. 2019.',
    github: 'https://github.com/The-Outlaws/cindr2/blob/master/README.md',
    deployed: 'http://cindr.herokuapp.com/',
  },
  {
    title: 'ALACK',
    date: '2019',
    imageUrl: '../images/alackScreenshot.png',
    imageAlt: 'A screenshot of a web application. A text box accepts a title from a book, a button submits that title, and the result tells the book sentiment',
    description: 'An app to answer that burning question: will this classic novel make me cry?',
    technologies: 'Vue · Express · PostgreSQL · Sequelize · Google Sentiment Analysis API',
    team: 'Solo project. 2019.',
    github: 'https://github.com/julia-catalano/alack',
    deployed: null,
  },
  {
    title: 'TO-MA-TO TO-MAH-TO',
    date: '2019',
    imageUrl: '../images/graceShopperScreenshot.png',
    imageAlt: 'A screenshot of a web application. An e-commerce website selling tomatoes.',
    description: 'A mock e-commerce website that offers fresh tomato plants from our garden.',
    technologies: 'Node · Express · React · Redux · PostgreSQL · Sequelize',
    team: 'Developed in collaboration with Jacqueline Zheng, Kat Le, and Pelin Dogan. 2019.',
    github: 'https://github.com/The-Hedwigs/grace-shopper',
    deployed: 'http://grace-shopper-1907.herokuapp.com',
  },
]

module.exports = projects
