const projects = [
  {
    title: 'stoop',
    date: '2019/2020/in development',
    imageUrl: '',
    imageAlt: '',
    description: 'A social cat spotting app, for spotting Brooklyn stoop cats.',
    technologies: 'Node.js, Express, React, Redux, Google Maps API, PostgreSQL, Sequelize',
    team: 'Solo project.',
    github: '',
    deployed: null,
  },
  {
    title: 'cindr',
    date: '2019',
    imageUrl: '',
    imageAlt: '',
    description: 'A choose-your-own-adventure style dating app. Instead of filling out lengthy profiles with basic information, users are matched based on an interactive experience that gives insight to their personality.',
    technologies: 'Phaser3, React, Redux, React-Redux, Node.js, Express, PostgreSQL, Sequelize, Socket.io',
    team: 'Developed in collaboration with Petra Laohakul, Darshin Van Parijs, and Kimberly Zawacki.',
    github: 'https://github.com/The-Outlaws/cindr2/blob/master/README.md',
    deployed: 'http://cindr.herokuapp.com/',
  },
  {
    title: 'alack',
    date: '2019',
    imageUrl: '',
    imageAlt: '',
    description: 'An app to answer that burning question: will this classic novel make me cry?',
    technologies: 'Vue.js, Express, PostgreSQL, Sequelize, Google Sentiment Analysis API',
    team: 'Solo project.',
    github: 'https://github.com/julia-catalano/alack',
    deployed: null,
  },
  {
    title: 'to-ma-to to-mah-to',
    date: '2019',
    imageUrl: '',
    imageAlt: '',
    description: 'A mock e-commerce website that offers fresh tomato plants from our garden. Built by members of the 1907 Grace Hopper cohort to fulfill the requirements for the Grace Shopper project.',
    technologies: 'Node.js, Express, React, Redux, PostgreSQL, Sequelize',
    team: 'Developed in collaboration with Jacqueline Zheng, Kat Le, and Pelin Dogan',
    github: 'https://github.com/The-Hedwigs/grace-shopper',
    deployed: 'http://grace-shopper-1907.herokuapp.com',
  },
]

module.exports = projects
